* Learning Rust
Follows the Rust book, with exercises chosen by me at certain points.

** Compiling
Simple compilation can be accomplished via rustc
#+BEGIN_SRC
 $ rustc hello_world/main.rs && ./hello_world/main
  >>>  "Hello, World!"
#+END_SRC

** Cargo (package management with "crates")
*** Getting Started
#+BEGIN_SRC
 $ cargo new hello_cargo
 $ cd hello_cargo
#+END_SRC
Note that by default cargo will inistialize a git repo
if one does not already exist. You can override this behavior
with
#+BEGIN_SRC
 $ cargo new --vcs=none hello_cargo
#+END_SRC
Notice that the Cargo.toml file more or less is resemblant of say a
package.json file--dependencies, i.e. third-party packages are known
as "crates" in Rust jargon.
We can build a Rust project via
#+BEGIN_SRC
 $ cargo build
#+END_SRC
and note that the compiled executable will exist in the target/debug
directory.
#+BEGIN_SRC
 $ ./target/debug/hello_cargo
#+END_SRC
Should print "Hello, Cargo!" and finally,
#+BEGIN_SRC
 $ cargo run
#+END_SRC
should both build and then run the project.

*** Additional Commands
**** Checking without compiling
#+BEGIN_SRC
 $ cargo check 
#+END_SRC
**** Cleaning old executables
#+BEGIN_SRC
 $ cargo clean 
#+END_SRC
**** Building for release
This will compile with optimizations, the resultant executable will
exist inside target/release rather than target/debug.
#+BEGIN_SRC
 $ cargo build --release
#+END_SRC

** Problems
NOTE: when working with Crates, you will NOT KNOW which methods
and functions to call from a crate, so each crate has documentation
for it's usage. You can build HTML documentation for a crate by
simply running:
#+BEGIN_SRC
 cargo doc --open 
#+END_SRC
*** Guessing Game (from Book)
**** Basics
Simple program which reads from stdin, checks against random number
then outputs success/failure.
#+BEGIN_SRC
 ./guessing_game 
#+END_SRC
The Cargo.toml file includes a dependency to generate random numbers.
Note that we can add this dependency explicitly, or install a library
by use of:
#+BEGIN_SRC
 $ cargo add rand 
#+END_SRC
Cargo uses Semantic Versioning--meaning that 0.8.5 is actually shorthand
for ^0.8.5 which means any version which at least 0.8.5 but before 0.9.0
(next major release).

**** Comparing Guesses and Better Feedback
